### ISSUE TITLE
Global Cookie Message in wrong position

### ISSUE THREAD

**Issue by jim-coffey** [hmrc/govuk-template#2]
Perhaps this is a none issue, but HMRC Developer Hub is using managed library resources in their Play apps, which pull in this template, but it seems to be displaying the global cookie message in the wrong place, after the black GOV.UK page header, rather than before it, right at the top of the page.

## Bad - this template
![screen shot 2016-12-22 at 08 51 40](https://cloud.githubusercontent.com/assets/8742105/21420234/53717032-c824-11e6-86fe-2cd8ab495a2c.png)

## Good - most gov sites
![screen shot 2016-12-22 at 08 53 15](https://cloud.githubusercontent.com/assets/8742105/21420229/4d65cb02-c824-11e6-9489-1cfd7cde1208.png)

This seems inconsistent with the rest of the gov.uk estate where the cookie banner is the first thing displayed in the page.

Obviously this is a global `breaking change`, but seems like it should be repositioned as most "top-displayed" cookie warnings are at the very top of the page.

**Comment by danewatts** [comment]
Closing as over 2 years old
