### ISSUE TITLE
Document language not updated when switching between Welsh/English

### ISSUE THREAD

**Issue by adamliptrot-oc** [hmrc/govuk-template#6]
When the Welsh/English language selector is enabled the document language ('lang' attribute on the html element) is not updated to reflect the change.
GovUK template has been updated to allow setting of the lang attribute via a parameter.

**Comment by tyagikumarvineet** [comment]
@rpowis Could you please advise?

**Comment by Jxr227** [comment]
I believe this is fixed in a recent PR https://github.com/hmrc/govuk-template/pull/68

**Comment by danewatts** [comment]
No response on whether fix was successful. Closing
